name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Tests with Gradle
        run: bundle exec fastlane test
